config/routes.rb
Rails.application.routes.draw do

  resources :joke_contents
  controller :joke_contents do
    post 'like_content' => :like_method
    post 'dislike_content' => :dislike_method
  end

  get 'dashboard/index', as: 'dashboard'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  get 'home_page/index'

  root 'home_page#index' ,as: "home_page"

end

app/models/joke_content.rb
class JokeContent < ActiveRecord::Base
  belongs_to :user

  def self.dislike(content_id)
    jokecontent = JokeContent.find(content_id)
    if jokecontent
      jokecontent.dislike_count += 1
      jokecontent.save
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :joke_contents, dependent: :destroy

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index

  end
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def index
    has_content_checks = cookies[:joke_content_has_checked] ? cookies[:joke_content_has_checked].split(",").map(&:to_i) : []

    if !has_content_checks.any?
      @joke_content = JokeContent.first
    else
      @joke_content = JokeContent.where('id NOT IN (?)',has_content_checks).first
    end
  end

end

app/controllers/joke_contents_controller.rb
class JokeContentsController < ApplicationController
  before_action :set_joke_content, only: [:show, :edit, :update, :destroy]

  # GET /joke_contents
  # GET /joke_contents.json
  def index
    @joke_contents = JokeContent.all
  end

  # GET /joke_contents/1
  # GET /joke_contents/1.json
  def show
  end

  # GET /joke_contents/new
  def new
    @joke_content = JokeContent.new
  end

  # GET /joke_contents/1/edit
  def edit
  end

  # POST /joke_contents
  # POST /joke_contents.json
  def create
    user = User.find_by(id: session[:user_id])
    @joke_content = user.joke_contents.new(joke_content_params)
    @joke_content.like_count = 0
    @joke_content.dislike_count =0

    respond_to do |format|
      if @joke_content.save
        format.html { redirect_to @joke_content, notice: 'Joke content was successfully created.' }
        format.json { render :show, status: :created, location: @joke_content }
      else
        format.html { render :new }
        format.json { render json: @joke_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /joke_contents/1
  # PATCH/PUT /joke_contents/1.json
  def update
    respond_to do |format|
      if @joke_content.update(joke_content_params)
        format.html { redirect_to @joke_content, notice: 'Joke content was successfully updated.' }
        format.json { render :show, status: :ok, location: @joke_content }
      else
        format.html { render :edit }
        format.json { render json: @joke_content.errors, status: :unprocessable_entity }
      end
    end
  end

  def content_check(content_id)
    str = cookies[:joke_content_has_checked]? cookies[:joke_content_has_checked] : ""
    if str == ""
      str = content_id
    else
      str = str + "," + content_id
    end
    cookies[:joke_content_has_checked] = str

  end

  def like_method
    content_check(params[:id])

    jokecontent = JokeContent.find(params[:id])
    if jokecontent
      jokecontent.like_count += 1
      jokecontent.save
    end
    redirect_to home_page_path
  end

  def dislike_method
    content_check(params[:id])

    JokeContent.dislike(params[:id])
    redirect_to home_page_path
  end

  # DELETE /joke_contents/1
  # DELETE /joke_contents/1.json
  def destroy
    @joke_content.destroy
    respond_to do |format|
      format.html { redirect_to joke_contents_url, notice: 'Joke content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_joke_content
      @joke_content = JokeContent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def joke_content_params
      params.require(:joke_content).permit(:title, :content, :like_count, :dislike_count)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    id = session[:user_id]
    if id
      redirect_to dashboard_path
    end
  end

  def create
    user = User.find_by(username: params[:username])
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      session[:username] = user.username
      redirect_to dashboard_path
    else
      redirect_to login_path, alert: "Invalid username or password"
    end
  end

  def destroy
    session[:user_id] = nil
    session[:username] = nil
    cookies[:joke_content_has_checked] = nil
    redirect_to home_page_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/joke_contents_helper.rb
module JokeContentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.haml
%h1 Dashboard#index
%p Find me in app/views/dashboard/index.html.haml

app/views/home_page/index.html.haml
%div.titleofhomepage
  %h3= "Wellcome to JokeQuote, happy everyday and never feel sad"
  %h5= "If you sad, remember has many don't have tooth"
-if @joke_content
  %div.joke_content_homepage
    %h4= @joke_content.title
    %h5= @joke_content.content
  %div.buttonarea
    = link_to 'This funny', like_content_path(id: @joke_content.id), method: :post, :class => 'btn btn-primary button_link'
    = link_to 'This not funny', dislike_content_path(id: @joke_content.id), method: :post, :class => 'btn btn-success button_link'
-else
  %div.joke_content_homepage
    %h3= "Hết truyện rồi, mời bạn ngày mai quay lại nhé, chúc bạn một ngày tốt lạnh"

app/views/joke_contents/_form.html.haml
= form_for @joke_content, html: { class: "form form-horizontal joke_content" } do |f|
  .form-group
    = f.label :title, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :title, class: 'form-control', required: true
    = f.error_span(:title)
  .form-group
    = f.label :content, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_area :content, class: 'form-control', required: true
    = f.error_span(:content)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil,class: 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), joke_contents_path, :class => 'btn btn-default'

app/views/joke_contents/edit.html.haml
- model_class = JokeContent
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/joke_contents/index.html.haml
- model_class = JokeContent
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:content)
      %th= model_class.human_attribute_name(:like_count)
      %th= model_class.human_attribute_name(:dislike_count)

      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @joke_contents.each do |joke_content|
      %tr
        %td= link_to joke_content.id, joke_content_path(joke_content)
        %td= joke_content.title
        %td= joke_content.content
        %td= joke_content.like_count
        %td= joke_content.dislike_count
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_joke_content_path(joke_content), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), joke_content_path(joke_content), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_joke_content_path, :class => 'btn btn-primary'

app/views/joke_contents/new.html.haml
- model_class = JokeContent
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/joke_contents/show.html.haml
- model_class = JokeContent
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = @joke_content.title
%p
  %strong= model_class.human_attribute_name(:content) + ':'
  %br
  = @joke_content.content


= link_to t('.back', :default => t("helpers.links.back")), joke_contents_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_joke_content_path(@joke_content), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), joke_content_path(@joke_content), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Jokequote"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href="/") Jokequote
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav.navbar-right
            %li= link_to "Joke Contents", joke_contents_url
            %li= link_to "", "/path2"
            %li
              - id = session[:user_id]
              - if id
                - name = session[:username]
                %h4 Wellcome you, #{name}
                %h5= button_to 'Logout', logout_path, method: :delete , :class => "btn btn-xs btn-primary"
              - else
                %h4 Wellcome you to our site
                %h5= button_to 'Login', login_path, method: :get, :class => "btn btn-xs btn-success"




    .container
      .row
        = bootstrap_flash
        = yield

      %footer
        %hr/
        %p= "dadajkdaskjd asbb kbsdhbakb sbdjbhja bdshbhyas d bhjbhkjsdbabsdb jkabsdaj ksd jabsj dbajsbdakjsbdjka bsdjabdbasdjab jsdbjabdjab hjdbajsbdjassb djasbdjasd dadajkdaskjd asbb kbsdhbakb sbdjbhja bdshbhyas d bhjbhkjsdbabsdb jkabsdaj ksd jabsj dbajsbdakjsbdjka bsdjabdbasdjab jsdbjabdjab hjdbajsbdjassb djasbdjasd dadajkdaskjd asbb kbsdhbakb sbdjbhja bdshbhyas d bhjbhkjsdbabsdb jkabsdaj ksd jabsj dbajsbdakjsbdjka bsdjabdbasdjab jsdbjabdjab hjdbajsbdjassb djasbdjasd dadajkdaskjd asbb kbsdhbakb sbdjbhja "
        %p &copy; Company 2015

app/views/users/_form.html.haml
= form_for @user, html: { class: "form form-horizontal user" } do |f|
  .form-group
    = f.label :username, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :username, class: 'form-control', required: true
    = f.error_span(:username)
  .form-group
    = f.label :email, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :email, class: 'form-control', required: true
    = f.error_span(:email)
  .form-group
    = f.label :password, class: 'control-label col-lg-2'
    .col-lg-10
      = f.password_field :password, class: 'form-control', required: true
    = f.error_span(:password)
  .form-group
    = f.label :password_confirmation, class: 'control-label col-lg-2'
    .col-lg-10
      = f.password_field :password_confirmation, class: 'form-control', required: true
    = f.error_span(:password_confirmation)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil,class: 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn btn-default'

app/views/users/edit.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/users/index.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:username)
      %th= model_class.human_attribute_name(:email)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.id, user_path(user)
        %td= user.username
        %td= user.email
        %td=l user.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(user), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_user_path, :class => 'btn btn-primary'

app/views/users/new.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/users/show.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:username) + ':'
  %br
  = @user.username
%p
  %strong= model_class.human_attribute_name(:email) + ':'
  %br
  = @user.email
%p
  %strong= model_class.human_attribute_name(:password_digest) + ':'
  %br
  = @user.password_digest


= link_to t('.back', :default => t("helpers.links.back")), users_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(@user), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(@user), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'